source('./Functions/myPalette.R')
source('./Functions/NanoMean.R')
source('./Functions/InnerFilter.R')
source('./Functions/PARAFAC.cube.design.R')
source('./Functions/plot.eem.go.richard.R')
source('./Functions/plot.integrate.RAMAN.R')
source('./Functions/read.EEM.Richard.R')
source('./Functions/subtract.blank.plot.EEMs.Richard.R')
source('./Functions/plot.integrate.RAMAN.go.R')
source('./Functions/PlotAllEEM.R')
source('./Functions/ExportEEM.R')
require(stringr)
require(stringdist)

cube=PARAFAC.cube.design()
